Web/Controllers/BADetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using DataTransferObject;
using ServiceLayer;

namespace Web.Controllers
{
    public class BADetailsController : BaseController
    {
        //
        // GET: /BADetails/

        #region Views

        public ActionResult BALandingPage()
        {
            return View();
        }

        public ActionResult BAPayDepositAmountPage()
        {
            return View();
        }

        public ActionResult BACheckCommissionAmountPage()
        {
            return View();
        }

        public ActionResult BACreateTicketPage(TicketDTO ticket)
        {
            GoodsTypeService goodsType = new GoodsTypeService();
            List<GoodsTypeDTO> lstGoods = goodsType.GetAllGoodsType();
            ViewBag.GoodsTypeDTO = lstGoods;

            TonnageService tService = new TonnageService();
            List<TonnageDTO> lstTonnage = tService.GetAllTonnageDetails();
            ViewBag.TonnageDTO = lstTonnage;
            if (ticket == null)
            {
                //ModelState.Clear();
                

                //ticket = new TicketDTO();
                //ticket.GoodsTypeDTO = new GoodsTypeDTO();
                //ticket.TonnageDTO = new TonnageDTO();
            }


            //if (ticket != null)
            //{
            //    if (ticket.TicketCreationStatus == -1)
            //    {
            //        ViewBag.Message = "Ticket Created Successfully";
            //    }
            //    else if (ticket.TicketCreationStatus == 1)
            //    {
            //        ViewBag.Message = "Driver details insertion Failed. Please Try again";
            //    }
            //    else if (ticket.TicketCreationStatus == 2)
            //    {
            //        ViewBag.Message = "Vehicle details insertion Failed. Please Try again";
            //    }
            //    else if (ticket.TicketCreationStatus == 3)
            //    {
            //        ViewBag.Message = "Registration No exists";
            //    }
            //}

            return View(ticket);
        }

        public ActionResult BAViewTicketsPage()
        {
            int userId = GetUserId();
            TicketService tService = new TicketService();
            List<TicketDTO> tickets = tService.GetTicketsByUserId(userId);
            return View(tickets);
        }

        public ActionResult BAUpdateVehicleLocationPage()
        {
            return View();
        }

        public ActionResult BAUpdateDriverDetailsPage()
        {
            return View();
        }

        public ActionResult BAEnableorDisableVehiclePage()
        {
            return View();
        }

        public ActionResult BAUpdateVehicleDetailsPage()
        {

            return View();
        }

        public ActionResult BAViewVehiclesRenewPage()
        {
            return View();
        }

        public ActionResult BAViewVehiclesListPage()
        {
            int userId = GetUserId();
            VehicleService vService = new VehicleService();
            List<VehicleDTO> vehicles = vService.GetVehiclesListForBA(userId);
            return View(vehicles);
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitTicket(TicketDTO ticket, HttpPostedFileBase InsurancePhoto, IEnumerable<HttpPostedFileBase> photo, HttpPostedFileBase RCBookPhoto, HttpPostedFileBase PermitPhoto, HttpPostedFileBase fcPhoto
            , HttpPostedFileBase DriverPhoto)
        {
            int userId = GetUserId();
            TicketService tService = new TicketService();
            int result;
            if (ticket != null)
            {
                result = tService.CreateTicket(ticket, InsurancePhoto, photo, RCBookPhoto, PermitPhoto, fcPhoto, DriverPhoto, userId);
                ViewBag.Result = result;
            }
            GoodsTypeService goodsType = new GoodsTypeService();
            List<GoodsTypeDTO> lstGoods = goodsType.GetAllGoodsType();
            ViewBag.GoodsTypeDTO = lstGoods;

            TonnageService tonService = new TonnageService();
            List<TonnageDTO> lstTonnage = tonService.GetAllTonnageDetails();
            ViewBag.TonnageDTO = lstTonnage;

            return View("BACreateTicketPage");
        }  

        #endregion

        #region JsonResult
        public JsonResult GetGoodsType()
        {
            GoodsTypeService goodsType = new GoodsTypeService();
            List<GoodsTypeDTO> lstGoods = goodsType.GetAllGoodsType();
            return Json(lstGoods, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTonnageDetails()
        {
            TonnageService tService = new TonnageService();
            List<TonnageDTO> lstTonnage = tService.GetAllTonnageDetails();
            return Json(lstTonnage, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Private Methods
        private int GetUserId()
        {
            var identity = User.Identity as ClaimsIdentity;
            var userId = identity.Claims.FirstOrDefault().Value;
            return Convert.ToInt32(userId);
        }
        #endregion
    }
}

Web/Controllers/DHDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using DataTransferObject;
using ServiceLayer;

namespace Web.Controllers
{
    public class DHDetailsController : BaseController
    {
        //
        // GET: /DHDetails/
        #region Public Methods
        public ActionResult DHLandingPage()
        {
            int userId = GetUserId();
            TicketService tService = new TicketService();
            List<TicketDTO> tickets = tService.GetDHTickets(userId);
            return View();
        }

        public ActionResult DHViewTeamPage()
        {
            return View();
        }

        public ActionResult DHViewRemainderListPage()
        {
            return View();
        }

        public ActionResult DHViewComplaintReportPage()
        {
            return View();
        }

        public ActionResult DHViewTeamCommissionReportPage()
        {
            return View();
        }

        public bool DHApproveReject(int ticketId, string comment, int status)
        {
            TicketService tService = new TicketService();
            return tService.DHApproveReject(ticketId, comment, status);
        }
        #endregion

        #region Private Methods
        private int GetUserId()
        {
            var identity = User.Identity as ClaimsIdentity;
            var userId = identity.Claims.FirstOrDefault().Value;
            return Convert.ToInt32(userId);
        }
        #endregion
    }
}

Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataTransferObject;
using ServiceLayer;
using SystemFrameworks;
using System.Security.Principal;
using System.Web.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace Web.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public int LoginClick(string userName, string password)
        //{
        //    UserService userService = new UserService();
        //    var userDTO = userService.GetLoginUser(userName, password);
        //    //if (userDTO.UserId > 0)
        //    //{
        //    //    return RedirectToAction("LoggedIn", "Login",new {id = userDTO.UserId});
        //    //}
        //    //return View();
        //    if (userDTO.UserId > 0)
        //    {
        //        IdentityHelper.SignIn(userDTO.Name, userDTO.RoleId.ToString(), false);
        //        return userDTO.UserId;
        //    }
        //    return 0;
        //}

        [HttpPost]
        public int LoginClick(string userName, string password, bool chkRememberMe)
        {
            UserService userService = new UserService();
            var userDTO = userService.GetLoginUser(userName, password);
            if (userDTO != null && userDTO.UserId > 0)
            {
                IdentityHelper.SignIn(userDTO.Name, userDTO.RoleId.ToString(), chkRememberMe, userDTO.UserId);
                return userDTO.RoleId;

                //if (userDTO.RoleId == Convert.ToInt32(RoleDTO.UserRoles.SuperAdmin))
                //{
                //    return RedirectToAction("SALandingPage", "SADetails");
                //}
                //else if (userDTO.RoleId == Convert.ToInt32(RoleDTO.UserRoles.StateHead))
                //{
                //    return RedirectToAction("SHLandingPage", "SHDetails");
                //}
                //else if (userDTO.RoleId == Convert.ToInt32(RoleDTO.UserRoles.DistrictHead))
                //{
                //    return RedirectToAction("DHLandingPage", "DHDetails");
                //}
            }
            else
            {
                return 0;
            }
            //return RedirectToAction("Index");
        }


        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();
            IAuthenticationManager authenticationManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
            authenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            HttpContext.Response.Cache.SetExpires(DateTime.UtcNow.AddDays(-1));
            HttpContext.Response.Cache.SetValidUntilExpires(false);
            HttpContext.Response.Cache.SetRevalidation(HttpCacheRevalidation.AllCaches);
            HttpContext.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            HttpContext.Response.Cache.SetNoStore();
            
            return RedirectToAction("Index", "Home");
        }
        
    }
}

Web/Controllers/SADetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataTransferObject;
using ServiceLayer;

namespace Web.Controllers
{

    //public class BaseController : Controller
    //{
    //    public BaseController()
    //    {
    //        ViewBag.Role = "SA";
    //    }
    //}

    public class SADetailsController : BaseController
    {
        
        //[AllowAnonymous]
        public ActionResult SALandingPage()
        {
            
            return View();
        }

        public ActionResult SAViewEmployeesPage()
        {
            UserService uService = new UserService();
            List<UserDTO> lstUsers = uService.GetAllUsers();
            return View(lstUsers);
        }

        public ActionResult SACreateUserPage()
        {
            return View();
        }

        public ActionResult SAChangeTonnageCostPage()
        {
            return View();
        }

        public int SubmitUserDetails(UserDTO userDTO,PersonalDTO personalDTO,CompanyDTO companyDTO,PartnerDTO partnerDTO,BankDTO bankDTO,AccountDTO accountDTO)
        {
            UserService uService = new UserService();
            int result = uService.CreateUser(userDTO, personalDTO, companyDTO, partnerDTO, bankDTO, accountDTO);
            return result;
        }

        public double TonnageChange(int tonnageId)
        {
            TonnageService tonnageService = new TonnageService();
            return tonnageService.TonnageChange(tonnageId);
        }

        public bool UpdateTonnage(int tonnageId, double cost)
        {
            TonnageService tonnageService = new TonnageService();
            return tonnageService.UpdateTonnage(tonnageId, cost);
        }

        #region JsonResult
        public JsonResult GetUserRoles()
        {
            RoleService roleService = new RoleService();
            List<RoleDTO> lstRoles = roleService.GetUserRoles();
            return Json(lstRoles, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStates(int countryId)
        {
            StateService stateService = new StateService();
            List<StateDTO> lstStates = stateService.GetStates(countryId);
            return Json(lstStates, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDistrict(int stateId)
        {
            DistrictService districtService = new DistrictService();
            List<DistrictDTO> lstDistrict = districtService.GetDistricts(stateId);
            return Json(lstDistrict, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRtos(int districtId)
        {
            RTOService rtoService = new RTOService();
            List<RtoDTO> lstRTO = rtoService.GetRtos(districtId);
            return Json(lstRTO, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPincode(int rtoId)
        {
            PinCodeService pcService = new PinCodeService();
            List<PinCodeDTO> lstPc = pcService.GetPinCode(rtoId);
            return Json(lstPc, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCountry()
        {
            CountryService cService = new CountryService();
            List<CountryDTO> lstCountry = cService.GetCountry();
            return Json(lstCountry, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBanksInIndia()
        {
            BankService bankService = new BankService();
            List<BanksInIndiaDTO> lstBanks = bankService.GetBanksInIndia();
            return Json(lstBanks, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTonnageDetails()
        {
            TonnageService tService = new TonnageService();
            List<TonnageDTO> lstTonnage = tService.GetAllTonnageDetails();
            return Json(lstTonnage, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Web/Controllers/SHDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class SHDetailsController : BaseController
    {
        //
        // GET: /SHDetails/

        public ActionResult SHLandingPage()
        {
            return View();
        }

        public ActionResult SHViewTeamPage()
        {
            return View();
        }

        public ActionResult SHViewComplaintReportPage()
        {
            return View();
        }

        public ActionResult SHViewTeamCommissionReportPage()
        {
            return View();
        }
    }
}

Web/Views/Login/Index.cshtml
@using System.Web.Mvc
@{    
    Layout = "~/Views/Shared/_LoginPartial.cshtml";
}


<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/angular.min.js"></script>
<script src="~/Scripts/Login/Login.js"></script>
<script type="text/javascript"> 
    var loginUrl = '@Url.Action("LoginClick","Login")';
    var saLoginUrl = '@Url.Action("SALandingPage","SADetails")';
    var shLoginUrl = '@Url.Action("SHLandingPage","SHDetails")';
    var dhLoginUrl = '@Url.Action("DHLandingPage","DHDetails")';
    var baLoginUrl = '@Url.Action("BALandingPage","BADetails")';
</script>
<div data-ng-app="loginApp" data-ng-controller="LoginController" data-ng-Init="InitializeLogin()" class="hold-transition">
    <form id="IndexForm" novalidate>
        @*<p>User Name : <input type="text" id="txtUserName" name="txtUserName" data-ng-model="UserName" required/>
                <span style="color:red" data-ng-show="IndexForm.txtUserName.$dirty && IndexForm.txtUserName.$invalid"></span>
                <span style="color:red" data-ng-show="IndexForm.txtUserName.$error.required">Enter the User Name.</span>
            </p>

            <p>
                Password : <input type="password" id="txtPassword" name="txtPassword" data-ng-model="Password" required />
                <span style="color:red" data-ng-show="IndexForm.txtPassword.$dirty && IndexForm.txtPassword.$invalid"></span>
                <span style="color:red" data-ng-show="IndexForm.txtPassword.$error.required">Enter the Password.</span>
            </p>
            <p>
                <button type="submit" id="btnLogin" data-ng-click="Login()">Login</button>
            </p>*@

        <div class="login-box">
            <div class="login-logo">
                <b>Sign in to start your session</b>
            </div><!-- /.login-logo -->
            <div class="form-group" id="dvMessage" style="display:none">
                <label for="lblMessage" class="control-label label-danger" id="lblMessage" data-ng-model="lblMessage">{{lblMessage}}</label>
            </div>

            <div class="login-box-body">
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" placeholder="UserName" id="txtUserName" name="txtUserName" data-ng-model="UserName" required>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    <span style="color:red" data-ng-show="IndexForm.txtUserName.$dirty && IndexForm.txtUserName.$invalid"></span>
                    <span style="color:red" data-ng-show="IndexForm.txtUserName.$error.required">Enter the User Name.</span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" id="txtPassword" name="txtPassword" data-ng-model="Password" required class="form-control" placeholder="Password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    <span style="color:red" data-ng-show="IndexForm.txtPassword.$dirty && IndexForm.txtPassword.$invalid"></span>
                    <span style="color:red" data-ng-show="IndexForm.txtPassword.$error.required">Enter the Password.</span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox" id="ChkRememberMe"> Remember Me
                            </label>
                        </div>
                    </div><!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" id="btnLogin" data-ng-click="Login()" class="btn btn-primary btn-block btn-flat" 
                            data-ng-disabled="IndexForm.txtUserName.$dirty && IndexForm.txtUserName.$invalid || IndexForm.txtPassword.$dirty && IndexForm.txtPassword.$invalid">Sign In</button>
                    </div><!-- /.col -->
                </div>


                <a href="#">I forgot my password</a><br>
                <a href="#" class="text-center">Register a new membership</a>


            </div>
        </div>

    </form>
</div>